version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: laptopharbor
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: laptopharbor
    ports:
      - "5432:5432"

  backend:
    build: .
    environment:
      DB_HOST: DB
      DB_USER: laptopharbor
      DB_PASSWORD: secretpassword
      DB_NAME: laptopharbor
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U laptopharbor" ]
      interval: 5s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"

volumes:
  db-data: